# Generated by Django 4.1.7 on 2023-05-09 17:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('pay', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Senior Level', 'Senior Level')], max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Temporary', 'Temporary')], max_length=50)),
                ('industry', models.CharField(choices=[('Accounting', 'Accounting'), ('Airlines/Aviation', 'Airlines/Aviation'), ('Alternative Dispute Resolution', 'Alternative Dispute Resolution')], max_length=50)),
                ('requirements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authent.company')),
            ],
        ),
    ]
