# Generated by Django 4.2 on 2023-05-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='location',
        ),
        migrations.AlterField(
            model_name='opening',
            name='job_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='opening',
            name='level',
            field=models.CharField(max_length=50),
        ),
    ]
