# Generated by Django 4.2 on 2023-05-31 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0002_remove_opening_industry_remove_opening_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
