# Generated by Django 4.2 on 2023-05-31 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0003_opening_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
