# Generated by Django 4.2 on 2023-06-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0004_opening_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening',
            name='requirements',
        ),
    ]
