# Generated by Django 4.2 on 2023-06-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0007_apprentice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
