# Generated by Django 4.2 on 2023-06-08 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0008_alter_opening_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprentice',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
